In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/felita/Library/Mobile Documents/com~apple~CloudDocs/Documents/Programming/Jupyter/0. CNAM Projects/Projet_Inegalites/Data/taux-seropositivite.csv', sep=';')

In [3]:
data

,Géodes - Santé publique France,,.1
0,Référentiel géographique : France par département,,
1,Code,Libellé,Taux de sérologies positives pour VIH 2018
2,01,Ain,0.6
3,02,Aisne,0.7
4,03,Allier,1.6
...,...,...,...
101,974,Réunion,0.8
102,975,Miquelon-Langlade et Saint Pierre,NaN
103,976,Mayotte,2.7
104,977,Saint-Barthélemy,NaN
105,978,Saint-Martin,NaN

In [4]:
data = data[2:]
data.columns = ['Code', 'Département', 'Taux de séropositivité']